version: '3.8'

services:
  bot:
    build: .
    container_name: order-bot
    restart: always
    env_file: .env
    depends_on:
      - mongo
    networks:
      - bot-net-order
    # Remove the volumes mapping for production
    # volumes:
    #   - .:/app

  mongo:
    image: mongo:7.0
    container_name: mongo-db-order
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27019:27017"  # Optional: for external access
    volumes:
      - mongo-data:/data/db
    networks:
      - bot-net-order
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongo-data:

networks:
  bot-net-order:
    driver: bridge