const STEPS = {
    WAITING_FOR_LANGUAGE: 'WAITING_FOR_LANGUAGE',
    START: 'START',
    SHOW_CATEGORIES: 'SHOW_CATEGORIES',
    CATEGORY_SELECTED: 'CATEGORY_SELECTED',
    WAITING_FOR_DELIVERY_DATE: 'WAITING_FOR_DELIVERY_DATE',
    WAITING_FOR_DELIVERY_TIME: 'WAITING_FOR_DELIVERY_TIME',
    WAITING_FOR_CARD_OPTION: 'WAITING_FOR_CARD_OPTION', // New step for card option
    WAITING_FOR_CARD_MESSAGE: 'WAITING_FOR_CARD_MESSAGE', // New step for card message
    WAITING_FOR_ADDRESS: 'WAITING_FOR_ADDRESS',
    WAITING_FOR_PHONE: 'WAITING_FOR_PHONE',
    WAITING_FOR_PAYMENT_SCREENSHOT: 'WAITING_FOR_PAYMENT_SCREENSHOT',
    ORDER_CONFIRMED: 'ORDER_CONFIRMED'
};

const texts = {
    hy: {
        chooseLanguage: '🌸 Խնդրում ենք ընտրել Ձեր նախընտրած լեզուն։',
        changeLanguage: '🌐 Փոխել լեզուն',
        welcome: (name, shopName) => `🌷 Հարգելի ${name}, բարի գալուստ *${shopName}*-ի աշխարհ։\n\nԻ՞նչ կցանկանայիք անել։ 😊`,
        mainMenu: '🏠 Հետ վերադառնալ գլխավոր մենյու',
        mainMenuWelcome: '🌼 Դուք վերադարձել եք գլխավոր մենյու։ Ի՞նչ կցանկանայիք անել։ 😊',
        orderBouquet: '💐 Պատվիրել ծաղկեփունջ',
        aboutUs: '🌿 Մեր մասին',
        aboutUsContent: (hours) => `*🌸 Մեր մասին*\n\nՄենք ստեղծում ենք թարմ և գեղեցիկ ծաղկեփնջեր Ձեր յուրաքանչյուր առիթի համար։\n⏰ *Աշխատանքային ժամեր* 10:00-21:00`,
        contactUs: '📞 Կապվել մեզ հետ',
        contactUsContent: (phone) => `*📲 Կապ մեզ հետ*\n\n📞 *Հեռախոս*: ${phone}\nՄենք միշտ այստեղ ենք Ձեզ օգնելու համար։ 😊`,
        followInstagram: '🌟 Հետևել Instagram-ում',
        callNow: '📱 Զանգել հիմա',
        chooseCategory: '💐 Ընտրեք Ձեր կատարյալ ծաղկեփնջի կատեգորիան։',
        categoryNotFound: '😔 Ներողություն, կատեգորիան չի գտնվել։',
        categoryDetails: (name, description, priceMin, priceMax) => `*🌺 ${name}*\n\n${description}\n\n💰 *Գին*: ${priceMin} - ${priceMax} ֏`,
        imageNotAvailable: '📷 Հաշվի առեք, որ ծաղկեփնջի նկարը ժամանակավորապես անհասանելի է։',
        orderThisCategory: '🛒 Պատվիրել այս ծաղկեփունջը',
        chooseDeliveryDate: (name) => `📅 Ընտրեք առաքման ամսաթիվ *${name}* ծաղկեփնջի համար։`,
        dateSelected: (date) => `✅ Դուք ընտրել եք առաքման ամսաթիվ՝ *${date}*։\n\n⏰ Խնդրում ենք ընտրել առաքման ժամը։`,
        chooseDeliveryTime: '⏰ Ընտրեք առաքման ժամը։',
        timeSelected: (date, time) => `🕒 Դուք ընտրել եք առաքման ժամ՝ *${time}* (${date})։\n\n💌 Ցանկանու՞մ եք ավելացնել բացիկ Ձեր պատվերին։`,
        includeCard: '💌 Ավելացնել բացիկ', // New text for card option
        skipCard: '⏭ Շարունակել առանց բացիկի', // New text for skipping card
        cardMessagePrompt: '✍️ Խնդրում ենք մուտքագրել բացիկի հաղորդագրությունը։\n*Օրինակ*: Շնորհավոր ծնունդդ, սիրելիս։', // New text for card message
        invalidCardMessage: '❌ Խնդրում ենք մուտքագրել վավեր հաղորդագրություն (մինչև 200 նիշ)։', // New text for invalid card message
        invalidDate: '❌ Անվավեր ամսաթիվ։ Խնդրում ենք ընտրել նոր ամսաթիվ։',
        pastDateOrClosed: '⚠️ Ընտրված ամսաթիվը անցյալում է կամ խանութը փակ է։ Խնդրում ենք ընտրել այլ ամսաթիվ։',
        pastTimeOrInvalid: '⚠️ Ընտրված ժամը անցյալում է կամ անվավեր է։ Խնդրում ենք ընտրել այլ ժամ։',
        noTimesForToday: '😔 Այսօր առաքման ժամեր չկան։ Խնդրում ենք ընտրել մեկ այլ ամսաթիվ։',
        selectAnotherDate: '🔙 Ընտրել այլ ամսաթիվ',
        addressExample: '📍 Խնդրում ենք մուտքագրել առաքման հասցեն։\n*Օրինակ*: Երևան, Կոմիտասի պող., 12, բն. 5',
        phoneExample: '📞 Խնդրում ենք մուտքագրել Ձեր հեռախոսահամարը։\n*Օրինակ*: +374 91 123456',
        invalidPhone: '❌ Անվավեր հեռախոսահամար։ Խնդրում ենք մուտքագրել ճիշտ ձևաչափով։',
        paymentInfo: '💳 Խնդրում ենք վճարումը կատարել բանկային քարտով կամ Idram հաշվով։\n*Բանկային քարտ*: 5501 0401 0052 9188 - Ameria\n 4578 8900 0851 0222 - Ineco\n*Idram հաշիվ*: +374 94 201122\nՀաշվի առեք, որ վճարումը պետք է կատարվի պատվերը հաստատելուց առաջ։',
        orderSummary: (name, quantity, date, time, price, address, phone, cardMessage) => `*🌟 Պատվերի ամփոփում*\n\n🛒 *Ծաղկեփունջ*: ${name}\n📦 *Քանակ*: ${quantity}\n📅 *Առաքման ամսաթիվ*: ${date}\n⏰ *Առաքման ժամ*: ${time}\n${cardMessage ? `💌 *Բացիկի հաղորդագրություն*: ${cardMessage}\n` : ''}💰 *Դրամ*: ${price}\n📍 *Հասցե*: ${address}\n📞 *Հեռախոս*: ${phone}\n\n💳 *Վճարման տվյալներ*:\n- *Բանկային քարտ*: 5501 0401 0052 9188 - Ameria\n 4578 8900 0851 0222 - Ineco\n- *Idram հաշիվ*: +374 94 201122\n\nԽնդրում ենք կատարել վճարումը և ավելացնել վճարման հաստատման սքրինշոթը։`,
        adminOrderSummary: (name, quantity, date, time, price, address, phone, cardMessage) => `*🌟 Նոր Պատվեր*\n\n🛒 *Ծաղկեփունջ*: ${name}\n📦 *Քանակ*: ${quantity}\n📅 *Առաքման ամսաթիվ*: ${date}\n⏰ *Առաքման ժամ*: ${time}\n${cardMessage ? `💌 *Բացիկի հաղորդագրություն*: ${cardMessage}\n` : ''}💰 *Դրամ*: ${price}\n📍 *Հասցե*: ${address}\n📞 *Հեռախոս*: ${phone}`,
        requestPaymentScreenshot: '📸 Խնդրում ենք ուղարկել վճարման հաստատման սքրինշոթը։',
        invalidPaymentScreenshot: '❌ Խնդրում ենք ուղարկել վճարման հաստատման սքրինշոթ (նկար)։',
        paymentScreenshotReceived: '✅ Վճարման սքրինշոթը ստացվել է։ Խնդրում ենք հաստատել պատվերը։',
        confirmOrder: '✅ Հաստատել պատվերը',
        cancelOrder: '❌ Չեղարկել պատվերը',
        orderConfirmed: '🎉 Ձեր պատվերը հաջողությամբ հաստատված է։ Շնորհակալություն, որ ընտրեցիք մեզ։ 😊',
        orderCancelled: '😔 Ձեր պատվերը չեղարկված է։ Կարող եք նորից փորձել։',
        errorOccurred: '😞 Տեղի է ունեցել սխալ։ Խնդրում ենք փորձել կրկին։',
        unknownCommand: '❓ Անհայտ հրաման։ Խնդրում ենք օգտագործել /start կամ /help։',
        prevMonth: '⬅️ Նախորդ ամիս',
        nextMonth: 'Հաջորդ ամիս ➡️',
        selectDateBack: '🔙 Հետ վերադառնալ ամսաթվի ընտրությանը',
        selectAddressBack: '🔙 Հետ վերադառնալ հասցեի ընտրությանը',
        selectTimeBack: '🔙 Հետ վերադառնալ ժամի ընտրությանը', // New text for time back
        weekDays: ['Երկ', 'Երք', 'Չրք', 'Հնգ', 'Ուրբ', 'Շբթ', 'Կիր']
    },
    ru: {
        chooseLanguage: '🌸 Пожалуйста, выберите язык.',
        changeLanguage: '🌐 Сменить язык',
        welcome: (name, shopName) => `🌷 Уважаемый(ая) ${name}, добро пожаловать в *${shopName}*! 😊\n\nЧто бы вы хотели сделать?`,
        mainMenu: '🏠 Вернуться в главное меню',
        mainMenuWelcome: '🌼 Вы вернулись в главное меню. Что бы вы хотели сделать? 😊',
        orderBouquet: '💐 Заказать букет',
        aboutUs: '🌿 О нас',
        aboutUsContent: (hours) => `*🌸 О нас*\n\nМы создаем свежие и красивые букеты для любого случая.\n⏰ *Часы работы* 10:00-21:00`,
        contactUs: '📞 Связаться с нами',
        contactUsContent: (phone) => `*📲 Связь с нами*\n\n📞 *Телефон*: ${phone}\nМы всегда здесь, чтобы помочь вам! 😊`,
        followInstagram: '🌟 Следить в Instagram',
        callNow: '📱 Позвонить сейчас',
        chooseCategory: '💐 Выберите категорию вашего идеального букета:',
        categoryNotFound: '😔 Категория не найдена.',
        categoryDetails: (name, description, priceMin, priceMax) => `*🌺 ${name}*\n\n${description}\n\n💰 *Цена*: ${priceMin} - ${priceMax} ֏`,
        imageNotAvailable: '📷 Обратите внимание, изображение букета временно недоступно.',
        orderThisCategory: '🛒 Заказать этот букет',
        chooseDeliveryDate: (name) => `📅 Выберите дату доставки для букета *${name}*.`,
        dateSelected: (date) => `✅ Вы выбрали дату доставки: *${date}*.\n\n⏰ Пожалуйста, выберите время доставки.`,
        chooseDeliveryTime: '⏰ Выберите время доставки.',
        timeSelected: (date, time) => `🕒 Вы выбрали время доставки: *${time}* (${date}).\n\n💌 Хотите добавить открытку к вашему заказу?`,
        includeCard: '💌 Добавить открытку', // New text for card option
        skipCard: '⏭ Продолжить без открытки', // New text for skipping card
        cardMessagePrompt: '✍️ Пожалуйста, введите сообщение для открытки.\n*Пример*: С днём рождения, дорогая!', // New text for card message
        invalidCardMessage: '❌ Пожалуйста, введите действительное сообщение (до 200 символов).', // New text for invalid card message
        invalidDate: '❌ Недействительная дата. Пожалуйста, выберите новую дату.',
        pastDateOrClosed: '⚠️ Выбранная дата в прошлом или магазин закрыт. Пожалуйста, выберите другую дату.',
        pastTimeOrInvalid: '⚠️ Выбранное время в прошлом или недействительно. Пожалуйста, выберите другое время.',
        noTimesForToday: '😔 Сегодня нет доступных временных интервалов. Пожалуйста, выберите другую дату.',
        selectAnotherDate: '🔙 Выбрать другую дату',
        addressExample: '📍 Пожалуйста, введите адрес доставки.\n*Пример*: Ереван, пр. Комитаса, 12, кв. 5',
        phoneExample: '📞 Пожалуйста, введите ваш номер телефона.\n*Пример*: +374 91 123456',
        invalidPhone: '❌ Недействительный номер телефона. Пожалуйста, введите в правильном формате.',
        paymentInfo: '💳 Пожалуйста, оплатите заказ через банковскую карту или Idram.\n*Банковская карта*: 5501 0401 0052 9188 - Ameria\n 4578 8900 0851 0222 - Ineco\n*Idram*: +374 94 201122\nОбратите внимание, что оплата должна быть произведена до подтверждения заказа.',
        orderSummary: (name, quantity, date, time, price, address, phone, cardMessage) => `*🌟 Итог вашего заказа*\n\n🛒 *Букет*: ${name}\n📦 *Количество*: ${quantity}\n📅 *Дата доставки*: ${date}\n⏰ *Время доставки*: ${time}\n${cardMessage ? `💌 *Сообщение на открытке*: ${cardMessage}\n` : ''}💰 *Цена*: ${price}\n📍 *Адрес*: ${address}\n📞 *Телефон*: ${phone}\n\n💳 *Платежные реквизиты*:\n- *Банковская карта*:  5501 0401 0052 9188 - Ameria\n 4578 8900 0851 0222 - Ineco\n- *Idram*: +374 94 201122\n\nПожалуйста, произведите оплату и отправьте скриншот подтверждения платежа.`,
        adminOrderSummary: (name, quantity, date, time, price, address, phone, cardMessage) => `*🌟 Новый заказ*\n\n🛒 *Букет*: ${name}\n📦 *Количество*: ${quantity}\n📅 *Дата доставки*: ${date}\n⏰ *Время доставки*: ${time}\n${cardMessage ? `💌 *Сообщение на открытке*: ${cardMessage}\n` : ''}💰 *Цена*: ${price}\n📍 *Адрес*: ${address}\n📞 *Телефон*: ${phone}`,
        requestPaymentScreenshot: '📸 Пожалуйста, отправьте скриншот подтверждения платежа.',
        invalidPaymentScreenshot: '❌ Пожалуйста, отправьте скриншот подтверждения платежа (изображение).',
        paymentScreenshotReceived: '✅ Скриншот платежа получен. Пожалуйста, подтвердите заказ.',
        confirmOrder: '✅ Подтвердить заказ',
        cancelOrder: '❌ Отменить заказ',
        orderConfirmed: '🎉 Ваш заказ успешно подтвержден! Спасибо, что выбрали нас! 😊',
        orderCancelled: '😔 Ваш заказ отменен. Можете попробовать снова.',
        errorOccurred: '😞 Произошла ошибка. Пожалуйста, попробуйте снова.',
        unknownCommand: '❓ Неизвестная команда. Пожалуйста, используйте /start или /help.',
        prevMonth: '⬅️ Предыдущий месяц',
        nextMonth: 'Следующий месяц ➡️',
        selectDateBack: '🔙 Вернуться к выбору даты',
        selectAddressBack: '🔙 Вернуться к выбору адреса',
        selectTimeBack: '🔙 Вернуться к выбору времени', // New text for time back
        weekDays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс']
    },
    en: {
        chooseLanguage: '🌸 Please select your preferred language.',
        changeLanguage: '🌐 Change language',
        welcome: (name, shopName) => `🌷 Dear ${name}, welcome to *${shopName}*! 😊\n\nWhat would you like to do?`,
        mainMenu: '🏠 Back to main menu',
        mainMenuWelcome: '🌼 You have returned to the main menu. What would you like to do? 😊',
        orderBouquet: '💐 Order a bouquet',
        aboutUs: '🌿 About us',
        aboutUsContent: (hours) => `*🌸 About us*\n\nWe create fresh and beautiful bouquets for every occasion.\n⏰ *Working hours* 10:00-21:00`,
        contactUs: '📞 Contact us',
        contactUsContent: (phone) => `*📲 Contact us*\n\n📞 *Phone*: ${phone}\nWe're always here to help you! 😊`,
        followInstagram: '🌟 Follow us on Instagram',
        callNow: '📱 Call now',
        chooseCategory: '💐 Choose the category of your perfect bouquet:',
        categoryNotFound: '😔 Category not found.',
        categoryDetails: (name, description, priceMin, priceMax) => `*🌺 ${name}*\n\n${description}\n\n💰 *Price*: ${priceMin} - ${priceMax} ֏`,
        imageNotAvailable: '📷 Please note that the bouquet image is temporarily unavailable.',
        orderThisCategory: '🛒 Order this bouquet',
        chooseDeliveryDate: (name) => `📅 Select delivery date for *${name}* bouquet.`,
        dateSelected: (date) => `✅ You have selected delivery date: *${date}*.\n\n⏰ Please select delivery time.`,
        chooseDeliveryTime: '⏰ Select delivery time.',
        timeSelected: (date, time) => `🕒 You have selected delivery time: *${time}* (${date}).\n\n💌 Would you like to include a card with your order?`,
        includeCard: '💌 Include a card', // New text for card option
        skipCard: '⏭ Continue without a card', // New text for skipping card
        cardMessagePrompt: '✍️ Please enter the message for the card.\n*Example*: Happy Birthday, my dear!', // New text for card message
        invalidCardMessage: '❌ Please enter a valid message (up to 200 characters).', // New text for invalid card message
        invalidDate: '❌ Invalid date. Please select a new date.',
        pastDateOrClosed: '⚠️ The selected date is in the past or the shop is closed. Please select another date.',
        pastTimeOrInvalid: '⚠️ The selected time is in the past or invalid. Please select another time.',
        noTimesForToday: '😔 No delivery times available for today. Please select another date.',
        selectAnotherDate: '🔙 Select another date',
        addressExample: '📍 Please enter the delivery address.\n*Example*: Yerevan, Komitas Ave., 12, apt. 5',
        phoneExample: '📞 Please enter your phone number.\n*Example*: +374 91 123456',
        invalidPhone: '❌ Invalid phone number. Please enter in the correct format.',
        paymentInfo: '💳 Please make the payment via bank card or Idram.\n*Bank Card*: 5501 0401 0052 9188 - Ameria\n 4578 8900 0851 0222 - Ineco\n*Idram*: +374 94 201122\nPlease ensure the payment is completed before confirming the order.',
        orderSummary: (name, quantity, date, time, price, address, phone, cardMessage) => `*🌟 Your order summary*\n\n🛒 *Bouquet*: ${name}\n📦 *Quantity*: ${quantity}\n📅 *Delivery date*: ${date}\n⏰ *Delivery time*: ${time}\n${cardMessage ? `💌 *Card message*: ${cardMessage}\n` : ''}💰 *Price*: ${price}\n📍 *Address*: ${address}\n📞 *Phone*: ${phone}\n\n💳 *Payment Details*:\n- *Bank Card*: 5501 0401 0052 9188 - Ameria\n 4578 8900 0851 0222 - Ineco\n- *Idram*: +374 94 201122\n\nPlease make the payment and upload a screenshot of the payment confirmation.`,
        adminOrderSummary: (name, quantity, date, time, price, address, phone, cardMessage) => `*🌟 New Order*\n\n🛒 *Bouquet*: ${name}\n📦 *Quantity*: ${quantity}\n📅 *Delivery date*: ${date}\n⏰ *Delivery time*: ${time}\n${cardMessage ? `💌 *Card message*: ${cardMessage}\n` : ''}💰 *Price*: ${price}\n📍 *Address*: ${address}\n📞 *Phone*: ${phone}`,
        requestPaymentScreenshot: '📸 Please upload a screenshot of the payment confirmation.',
        invalidPaymentScreenshot: '❌ Please upload a screenshot of the payment confirmation (image).',
        paymentScreenshotReceived: '✅ Payment screenshot received. Please confirm the order.',
        confirmOrder: '✅ Confirm order',
        cancelOrder: '❌ Cancel order',
        orderConfirmed: '🎉 Your order has been successfully confirmed! Thank you for choosing us! 😊',
        orderCancelled: '😔 Your order has been cancelled. You can try again.',
        errorOccurred: '😞 An error occurred. Please try again.',
        unknownCommand: '❓ Unknown command. Please use /start or /help.',
        prevMonth: '⬅️ Previous month',
        nextMonth: 'Next month ➡️',
        selectDateBack: '🔙 Back to date selection',
        selectAddressBack: '🔙 Back to address selection',
        selectTimeBack: '🔙 Back to time selection', // New text for time back
        weekDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    }
};

module.exports = { STEPS, texts };